# Generated by Django 6.0 on 2025-12-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitatii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bride_name',
            field=models.CharField(help_text='Name of the bride', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Date and time of the wedding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True, help_text='Extra info like dress code, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_name',
            field=models.CharField(help_text='Name of the groom', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Venue address or name', max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(blank=True, help_text='RSVP status', null=True),
        ),
        migrations.CreateModel(
            name='GeneratedInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(default='formal', max_length=50)),
                ('ai_text', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='inv_backgrounds/')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='inv_final/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitatii.event')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitatii.guest')),
            ],
        ),
    ]
