# Generated by Django 5.1.6 on 2025-12-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0002_socialaura"),
        ("birthdata", "0002_rename_name_birthdate_first_name_birthdate_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compatibility_score", models.IntegerField()),
                ("analysis", models.TextField()),
                ("short_verdict", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_a",
                        to="birthdata.birthdate",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_b",
                        to="birthdata.birthdate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("person_a", "person_b")},
            },
        ),
    ]
