# Generated by Django 5.1.6 on 2025-12-01 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID sesiune')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data vizualizării')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresă IP')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tours.tour', verbose_name='Tur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Vizualizare tur',
                'verbose_name_plural': 'Vizualizări tururi',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='TourCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data completării')),
                ('rating_given', models.BooleanField(default=False, verbose_name='Rating dat')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tours.tour', verbose_name='Tur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Completare tur',
                'verbose_name_plural': 'Completări tururi',
                'ordering': ['-completed_at'],
                'unique_together': {('tour', 'user')},
            },
        ),
    ]
