# Generated by Django 5.1.6 on 2025-12-01 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume locație')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitudine')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitudine')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('historical_info', models.TextField(blank=True, verbose_name='Informații istorice')),
                ('duration_minutes', models.IntegerField(default=10, verbose_name='Durată estimată (minute)')),
            ],
            options={
                'verbose_name': 'Locație',
                'verbose_name_plural': 'Locații',
                'ordering': ['tour', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/', verbose_name='Imagine')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legendă')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.location', verbose_name='Locație')),
            ],
            options={
                'verbose_name': 'Imagine locație',
                'verbose_name_plural': 'Imagini locații',
                'ordering': ['location', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('category', models.CharField(choices=[('istoric', 'Istoric'), ('cultural', 'Cultural'), ('gastronomic', 'Gastronomic'), ('viata_noapte', 'Viață de noapte')], max_length=20, verbose_name='Categorie')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preț (RON)')),
                ('duration', models.IntegerField(help_text='Durată în minute', verbose_name='Durată')),
                ('difficulty', models.CharField(choices=[('usor', 'Ușor'), ('mediu', 'Mediu'), ('dificil', 'Dificil')], default='usor', max_length=10, verbose_name='Dificultate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizare')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Imagine de copertă')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Tururi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tours.tour', verbose_name='Tur'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tours.comment', verbose_name='Răspuns la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tours.tour', verbose_name='Tur')),
            ],
            options={
                'verbose_name': 'Comentariu',
                'verbose_name_plural': 'Comentarii',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comentariu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Tur')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Review-uri',
                'ordering': ['-created_at'],
                'unique_together': {('tour', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OfflineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data descărcării')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Data expirării')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_content', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_downloads', to='tours.tour', verbose_name='Tur')),
            ],
            options={
                'verbose_name': 'Conținut offline',
                'verbose_name_plural': 'Conținut offline',
                'ordering': ['-downloaded_at'],
                'unique_together': {('user', 'tour')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data adăugării')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tours.tour', verbose_name='Tur')),
            ],
            options={
                'verbose_name': 'Favorit',
                'verbose_name_plural': 'Favorite',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
