# Generated by Django 5.1.6 on 2026-01-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID sesiune pentru utilizatori anonimi', max_length=100, verbose_name='ID Sesiune')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Început conversație')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizare')),
                ('preferences_extracted', models.JSONField(blank=True, default=dict, verbose_name='Preferințe extrase')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Conversație',
                'verbose_name_plural': 'Conversații',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilizator'), ('assistant', 'Asistent AI'), ('system', 'System')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tours.conversation', verbose_name='Conversație')),
            ],
            options={
                'verbose_name': 'Mesaj Chat',
                'verbose_name_plural': 'Mesaje Chat',
                'ordering': ['timestamp'],
            },
        ),
    ]
