# Generated by Django 5.1.6 on 2026-01-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_conversation_chatmessage 2'),
        ('tours', '0002_conversation_chatmessage'),
    ]

    operations = [
    ]
