# Generated by Django 5.1.6 on 2026-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_merge_20260116_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(choices=[('bucuresti', 'București'), ('cluj', 'Cluj-Napoca'), ('brasov', 'Brașov'), ('sibiu', 'Sibiu'), ('timisoara', 'Timișoara'), ('iasi', 'Iași')], default='bucuresti', max_length=20, verbose_name='Oraș'),
        ),
    ]
