# Generated by Django 5.1.6 on 2025-12-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birthdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="birthdate",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="birthdate",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
