# Generated by Django 5.2.5 on 2025-11-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='original_file',
        ),
        migrations.AddField(
            model_name='note',
            name='file_content',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='file_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
