# Generated by Django 5.2.5 on 2025-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_note_original_file_note_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_in_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_in_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
    ]
